export const data = [
  {id: 1, heading: "most popular", child: false, img: "/assets/img/contactUs/icons/mostPopular.png",
    innerInfo: [
      {id: 10, child: true, heading: "what happens if my deposit is not showing?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 11, child: true, heading: "How long does it take for deposits for show in my account?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 12, child: true, heading: "What happens if I sent my deposit to another address or if I deposited lower than the minimum amount?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 13, child: true, heading: "What are the rules to withdrawing my balance?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
    ]
  },
  {id: 2, heading: "account", child: false, img: "/assets/img/contactUs/icons/myAccount.png",
    innerInfo: [
      {id: 20, child: true, heading: "what happens if my deposit is not showing?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 21, child: true, heading: "How long does it take for deposits for show in my account?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 22, child: true, heading: "What happens if I sent my deposit to another address or if I deposited lower than the minimum amount?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 23, child: true, heading: "What are the rules to withdrawing my balance?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
    ]
  },
  {id: 3, heading: "deposits & withdrawals", child: false, img: "/assets/img/contactUs/icons/deposits.png",
    innerInfo: [
      {id: 30, child: true, heading: "what happens if my deposit is not showing?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 31, child: true, heading: "How long does it take for deposits for show in my account?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 32, child: true, heading: "What happens if I sent my deposit to another address or if I deposited lower than the minimum amount?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 33, child: true, heading: "What are the rules to withdrawing my balance?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
    ]
  },
  {id: 4, heading: "bonuses", child: false, img: "/assets/img/contactUs/icons/bonuses.png",
    innerInfo: [
      {id: 40, child: true, heading: "what happens if my deposit is not showing?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 41, child: true, heading: "How long does it take for deposits for show in my account?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 42, child: true, heading: "What happens if I sent my deposit to another address or if I deposited lower than the minimum amount?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 43, child: true, heading: "What are the rules to withdrawing my balance?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
    ]
  },
  {id: 5, heading: "the casino", child: false, img: "/assets/img/contactUs/icons/casino.png",
    innerInfo: [
      {id: 50, child: true, heading: "what happens if my deposit is not showing?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 51, child: true, heading: "How long does it take for deposits for show in my account?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 52, child: true, heading: "What happens if I sent my deposit to another address or if I deposited lower than the minimum amount?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 53, child: true, heading: "What are the rules to withdrawing my balance?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
    ]
  },
  {id: 6, heading: "security", child: false, img: "/assets/img/contactUs/icons/security.png",
    innerInfo: [
      {id: 60, child: true, heading: "what happens if my deposit is not showing?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 61, child: true, heading: "How long does it take for deposits for show in my account?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 62, child: true, heading: "What happens if I sent my deposit to another address or if I deposited lower than the minimum amount?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 63, child: true, heading: "What are the rules to withdrawing my balance?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
    ]
  },
  {id: 7, heading: "responsible gaming", child: false, img: "/assets/img/contactUs/icons/responsGaming.png",
    innerInfo: [
      {id: 70, child: true, heading: "what happens if my deposit is not showing?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 71, child: true, heading: "How long does it take for deposits for show in my account?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 72, child: true, heading: "What happens if I sent my deposit to another address or if I deposited lower than the minimum amount?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 73, child: true, heading: "What are the rules to withdrawing my balance?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
    ]
  },
  {id: 8, heading: "affiliate", child: false, img: "/assets/img/contactUs/icons/affiliate.png",
    innerInfo: [
      {id: 80, child: true, heading: "what happens if my deposit is not showing?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 81, child: true, heading: "How long does it take for deposits for show in my account?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 82, child: true, heading: "What happens if I sent my deposit to another address or if I deposited lower than the minimum amount?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
      {id: 83, child: true, heading: "What are the rules to withdrawing my balance?", text: " If your crypto deposit is now showing, this most likely means that it has not yet been confirmed in the blockchain, or that your wallet has not yet sent the funds, you can always check the blockchain to see if your transfer is visible there, or ask the support if you need a hand with this."},
    ]
  },
]